### ISSUE TITLE
Creating a new content-element

### ISSUE THREAD

**Issue by gww-its** [janborg/contao-ical-bundle#6]
After installing this extension i get following error-Message
`An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'ical_title' doesn't have a default value`
while creating a new content-element.
Contao: 5.3.3

**Comment by janborg** [comment]
Hi, 
I can't reproduce the error because I don't use a field "ical_title" in this extension. I suspect that the error is related to another extension that you have installed. 
Did you possibly install one of these extensions, or have had installed them and not updated the database correctly after deinstalling them? These extensions have a field "ical_title".

- https://github.com/cgoIT/contao-calendar-ical-bundle/
- https://github.com/Craffft/contao-calendar-ical-bundle

Regards
Jan
